### ISSUE TITLE
Xlog

### ISSUE THREAD

**Issue by johanromuald** [MokoBeaconX/mokoBeaconX_Android#6]
Hi,

I wrote simple app to start scan and then stop scan using your SDK, and then I get the results. Everything is working fine. I have one problem, when I open the application 2nd I am getting following error.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mcs.mcs.mymoko/com.mcs.mcs.mymoko.MainActivity}: java.lang.IllegalStateException: XLog is already initialized, do not initialize again.

Is there way to de-initialize the Xlog or MokoSupport  , when I close the application.

**Comment by liuwenzheng** [comment]
Sorry for the late reply.
We recommend MokoSupport initialization in a custom Application.
eg.
`public class BaseApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        MokoSupport.getInstance().init(getApplicationContext());
    }
}
`

**Comment by johanromuald** [comment]
Hi,
Thank you very much. It worked. 
Can you please let me know how to solve the following warning;
2020-05-18 12:05:48.195 20320-20320/com.mcs.mcs.mymoko I/mokoLog: 结束扫描Beacon
2020-05-18 12:05:48.196 20320-20320/com.mcs.mcs.mymoko D/BluetoothAdapter: STATE_ON
2020-05-18 12:05:48.197 20320-20320/com.mcs.mcs.mymoko D/BluetoothAdapter: STATE_ON
2020-05-18 12:05:48.197 20320-20320/com.mcs.mcs.mymoko D/BluetoothLeScanner: Stop Scan with callback
2020-05-18 12:05:48.197 20320-20823/com.mcs.mcs.mymoko W/System.err: java.io.IOException: Permission denied
2020-05-18 12:05:48.197 20320-20823/com.mcs.mcs.mymoko W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2020-05-18 12:05:48.197 20320-20823/com.mcs.mcs.mymoko W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
2020-05-18 12:05:48.197 20320-20823/com.mcs.mcs.mymoko W/System.err:     at java.io.File.createNewFile(File.java:1008)
2020-05-18 12:05:48.197 20320-20823/com.mcs.mcs.mymoko W/System.err:     at com.elvishew.xlog.printer.file.FilePrinter$Writer.open(FilePrinter.java:367)
2020-05-18 12:05:48.197 20320-20823/com.mcs.mcs.mymoko W/System.err:     at com.elvishew.xlog.printer.file.FilePrinter.doPrintln(FilePrinter.java:121)
2020-05-18 12:05:48.197 20320-20823/com.mcs.mcs.mymoko W/System.err:     at com.elvishew.xlog.printer.file.FilePrinter$Worker.run(FilePrinter.java:296)
2020-05-18 12:05:48.197 20320-20823/com.mcs.mcs.mymoko W/System.err:     at java.lang.Thread.run(Thread.java:919)

**Comment by liuwenzheng** [comment]
By default, Xlog writes the log to the SD root of the phone, so you need WRITE_EXTERNAL_STORAGE permission.Use this permission on mobile phones with Android system 6.0 and later, which requires user confirmation.You can use the code in the  GuideActivity.

**Comment by johanromuald** [comment]
Ok Thank you. You made my day.

**Comment by johanromuald** [comment]
Hi, 
Is there a way to turn-off the Xlog.  I do not require any logging.
Thank you.

**Comment by liuwenzheng** [comment]
Well,You need to change the code in the LogModule.
`
//        XLog.init(config, new AndroidPrinter(), filePrinter);
        XLog.init(config);
`

**Comment by johanromuald** [comment]
Thank you.
